// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/version.json",
    "/_app/immutable/*",
    "/cert-bi-specialist.jpg",
    "/cert-pl300.png",
    "/fonts/pretendard/LICENSE",
    "/fonts/pretendard/PretendardVariable.woff2",
    "/gapyear-hero-banner.jpg",
    "/hero-my-page-v2.webp",
    "/hero-preview-home.jpg",
    "/hero-submit.webp",
    "/logo.webp",
    "/reference-datastudio-logo-cropped.webp",
    "/reference-powerbi-logo-cropped.webp",
    "/reference-streamlit-logo-cropped.webp",
    "/reference-tableau-logo-cropped.webp",
    "/robots.txt",
    "/snowball-impact.webp",
    "/vision-snowball.webp"
  ]
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "C:\\workspace\\folio\\svelte_app\\.wrangler\\tmp\\pages-kmzI30\\bundledWorker-0.23809073213775844.mjs";
import { isRoutingRuleMatch } from "C:\\workspace\\folio\\svelte_app\\node_modules\\wrangler\\templates\\pages-dev-util.ts";
export * from "C:\\workspace\\folio\\svelte_app\\.wrangler\\tmp\\pages-kmzI30\\bundledWorker-0.23809073213775844.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=ck8gzm50g3p.js.map
